"""empty message

Revision ID: 062d342c3f67
Revises: b2eac028eff4
Create Date: 2026-02-23 20:22:43.940802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '062d342c3f67'
down_revision: Union[str, Sequence[str], None] = 'b2eac028eff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_buckets', sa.Column('period_start_local', sa.Date(), nullable=False))
    op.add_column('time_buckets', sa.Column('iana_timezone', sa.String(length=64), nullable=False))
    op.add_column('time_buckets', sa.Column('start_utc', sa.DateTime(timezone=True), nullable=False))
    op.add_column('time_buckets', sa.Column('end_utc', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('time_buckets', 'duration_seconds',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_timebucket_host_period'), 'time_buckets', type_='unique')
    op.create_unique_constraint('uq_timebucket_local', 'time_buckets', ['host_id', 'period_start_local', 'iana_timezone'])
    op.drop_column('time_buckets', 'updated_at')
    op.drop_column('time_buckets', 'period_start')
    op.drop_column('time_buckets', 'period_type')
    op.drop_column('time_buckets', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_buckets', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('time_buckets', sa.Column('period_type', postgresql.ENUM('DAY', 'WEEK', 'MONTH', name='period_type'), autoincrement=False, nullable=False))
    op.add_column('time_buckets', sa.Column('period_start', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('time_buckets', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint('uq_timebucket_local', 'time_buckets', type_='unique')
    op.create_unique_constraint(op.f('uq_timebucket_host_period'), 'time_buckets', ['host_id', 'period_type', 'period_start'], postgresql_nulls_not_distinct=False)
    op.alter_column('time_buckets', 'duration_seconds',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_column('time_buckets', 'end_utc')
    op.drop_column('time_buckets', 'start_utc')
    op.drop_column('time_buckets', 'iana_timezone')
    op.drop_column('time_buckets', 'period_start_local')
    # ### end Alembic commands ###
