"""Switch to daily time buckets

Revision ID: cd36cda02ed3
Revises: 062d342c3f67
Create Date: 2026-02-24 21:46:29.188165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd36cda02ed3'
down_revision: Union[str, Sequence[str], None] = '062d342c3f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_time_buckets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_id', 'date', name='uq_dailytimebucket_local')
    )
    op.drop_table('time_buckets')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_buckets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('host_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('period_start_local', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('iana_timezone', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('start_utc', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_utc', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], name=op.f('time_buckets_host_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('time_buckets_pkey')),
    sa.UniqueConstraint('host_id', 'period_start_local', 'iana_timezone', name=op.f('uq_timebucket_local'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('daily_time_buckets')
    # ### end Alembic commands ###
